name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mansona/npm-lockfile-version@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run lint

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm test

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run build
